4.0.0: Capital Support
DaPigGuy/libPiggyEconomy pull request #4
Opened 2022-03-01 06:56 UTC by Aericio

2022-03-18 11:58 UTC, SOF3 requested changes

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +        Capital::api($this->version, fn(Capital $api) => $this->selector = $api->completeConfig(libPiggyEconomy::$plugin->getConfig()->get("capital-selector")));
There should be separate selector configuration for each use case. Using the same selector for the whole plugin renders the multi account design useless because the user can only set the same account every time.

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +        $this->oracle = libPiggyEconomy::$plugin->getName();
the oracle can sometimes be a submodule, e.g. "Capital/Transfer". Consider passing an optional `?string $submodule` and `$this->oracle = $plugin->getName() . ($submodule !== null ? "/$submodule" : "");`.

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +        return "$";
The design philosophy is that user defines their own choice of currency symbol, and we should not force the same symbol to be used every time.

Also please consider leveraging InfoAPI, which is more consistent.

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +    public function takeMoney(Player $player, float $amount, ?callable $callback = null): void
I think it is a bad idea to make the callable nullable. You want to handle takeMoney result. You don't want to execute the transaction unconditionally.

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +            $difference = $balance - (int)$amount;
See SOF3/Capital#28

2022-03-18 11:58 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +    private string $version = "0.1.0";
Not a big problem, but personally I recommend writing the version every time, because this allows the plugin to continue working even if Capital is outdated as long as you don't use the new APIs everywhere.

2022-03-18 22:59 UTC, supercrafter333 commented
@Aericio

2022-03-19 03:57 UTC, SOF3 commented
To be honest, the best way to access all features of Capital is to mock the Capital API and polyfill them with BedrockEconomy and xplevel stuff.

2023-09-02 18:10 UTC, Endermanbugzjfc commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +        return "$";
So Virion 3 has "flat dependency" now, so it would be a lot easier to just pull InfoAPI here? (Capital is dead, tho.)

2023-09-03 14:34 UTC, SOF3 commented on src/DaPigGuy/libPiggyEconomy/providers/CapitalProvider.php
> +        return "$";
the point was that monetary unit shouldn't be used anywhere, though. Why can't you just put it in when you actually display?

2024-03-31 20:43 UTC, closed without merging